export const DIALOG_MESSAGES = {
  FIRST_RUN_CLICKED: "FIRST_RUN_CLICKED",
  DIALOG_INITIALIZED: "DIALOG_INITIALIZED",
  DIALOG_DRAFT_FINISHED_FROM_COMPOSE: "DIALOG_DRAFT_FINISHED_FROM_COMPOSE",
  DIALOG_DRAFT_FINISHED_FROM_REPLY: "DIALOG_DRAFT_FINISHED_FROM_REPLY",
  CLOSE_SETTINGS_DIALOG: "CLOSE_SETTINGS_DIALOG",
  SIGN_OUT_FROM_CHROME: "SIGN_OUT_FROM_CHROME",
};
